# Generated by Django 5.1.7 on 2025-03-11 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_reminder', models.CharField(choices=[('on', 'ON'), ('off', 'OFF')], default='on', max_length=3)),
                ('chat_notification', models.CharField(choices=[('on', 'ON'), ('off', 'OFF')], default='on', max_length=3)),
                ('announcement_notification', models.CharField(choices=[('on', 'ON'), ('off', 'OFF')], default='on', max_length=3)),
                ('reminder_frequency', models.IntegerField(default=24)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_setting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
